services:
  app:
    build: .
    image: mrs_project
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
      - /home/colorvax/go_code/movie_reservation_system/configs:/root/configs
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: movie_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
