port: "8080"

db:
    username: "postgres"
    host: "db"
    port: "5432"
    dbname: "movie_db"
    sslmode: "disable"
    password: "qwerty"
jwt: 
    jwtkey: pqowQIEHQWIHN19231XH!@#*8ADS
    accessttl: 15
    refreshttl: 7


